---
logging:
  level: INFO
  loggers:
    nagarro: DEBUG


#database settings
database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: root
  url: jdbc:mysql://localhost:3306/demo
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate.show_sql: true
    hibernate.format_sql: true
    hibernate.hbm2ddl.auto: update