---
logging:
  level: INFO
  loggers:
    nagarro: DEBUG


#database settings
database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: root
  url: jdbc:postgresql://localhost:5432/demo
