---
logging:
  level: INFO
  loggers:
    nagarro: DEBUG


#database settings
database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: root
  url: jdbc:postgresql://localhost:5432/demo
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.show_sql: true
    hibernate.format_sql: true
    hibernate.hbm2ddl.auto: update
  maxSize: 10
  minSize: 1
